

#include <SDL2/SDL.h>


extern const i32 SDL_QUIT;

// extern const struct SDL_Event;

// alias SDL_GLattr = u32;
// alias SDL_GLContext = void*;

extern fn SDL_Init(flags: u32) -> i32;
extern fn SDL_GL_SetAttribute(attr: SDL_GLattr, value: i32) -> i32;
extern fn SDL_CreateWindow(title: const char *, x: i32, y: i32, w: i32, h: i32, flags: u32) -> SDL_Window*;
extern fn SDL_GetError() -> const char *;
extern fn SDL_GL_CreateContext(window: SDL_Window*) -> SDL_GLContext;
extern fn SDL_GL_MakeCurrent(window: SDL_Window*, context: SDL_GLContext) -> i32;
extern fn SDL_GL_DeleteContext(context: SDL_GLContext) -> void;
extern fn SDL_DestroyWindow(window: SDL_Window*) -> void;
extern fn SDL_Quit() -> void;

extern fn SDL_PollEvent(event: SDL_Event*) -> i32;
extern fn SDL_GL_SwapWindow(window: SDL_Window*) -> void;
extern fn SDL_Delay(ms: u32) -> void;
extern fn SDL_GetTicks() -> u32;

